### Pandas + NumPy Data Cleaning — 30 Questions

In [2]:
# 1. Load the CSV using Pandas and display the first 10 rows.

import pandas as pd
df = pd.read_csv("C:\\Users\\DELL\\Downloads\\customer_data - customer_data.csv")
df.head(10)

,Customer ID,Age,income_usd,credit Score,tenure_years,monthly_visits,satisfaction,City,customer_segment,gender,is_active,churn_flag,signup_date,lead_source,notes_text
0,CUST-01861,45.86741673,28198.41033,660.5629176,5.274076,5.0,3.382150,Pune,consumer,NaN,Yes,No,2026-03-11,Referral,NaN
1,CUST-00354,47.76516428,61312.83129,838 pts,5.632826,9.0,NaN,Hyderabad,Consumer,Male,NaN,No,NaN,website,follow-up needed
2,CUST-01334,NaN,44199.67124,613.1327754,NaN,8.0,4.195157,Mumbai,Consumer,m,Yes,No,2024-09-20,Email,NaN
3,CUST-00906,62.72357805,56259.90961,720.2369862,2.029634,4.0,NaN,Chennai,Enterprise,m,N,No,2023-07-12,Website,normal
4,CUST-01290,NaN,31238.64196,549.1832523,2.648626,5.0,3.117326,Mumbai,Enterprise,Male,Yes,No,2024-08-06,NaN,???
5,CUST-01274,NaN,"$44,696",NaN,1.700044,12.0,NaN,Bengaluru,SMB,Male,Yes,Yes,21/07/2024,NaN,follow-up needed
6,CUST-00939,49.28347358,44108.07925,793.2135773,10.077820,7.0,3.872187,Kolkata,Consumer,NaN,yes,Yes,2023-08-14,google_ads,NaN
7,CUST-01732,37.63000983,80888.86264,850,4.489813,11.0,NaN,Pune,NaN,Female,N,No,NaN,NaN,good customer
8,CUST-00066,47.52016682,50011.55556,796.794099,9.074520,4.0,3.694925,Pune,SMB.,m,No,NaN,2021-03-08,Social,NaN
9,CUST-01324,NaN,84410.30824,482.3950729,6.820629,3.0,2.636945,Mumbai,Consumer,M,no,No,2024-09-10,Website,normal

In [3]:
# 2. Check the number of rows and columns in the dataset.

df.shape

(2000, 15)

In [4]:
# 3. Display all column names and identify which column names contain leading/trailing spaces or inconsistent capitalization.

df.columns

Index(['Customer ID', 'Age', 'income_usd', 'credit Score', 'tenure_years',
       'monthly_visits', 'satisfaction', 'City', 'customer_segment', 'gender',
       'is_active', 'churn_flag', 'signup_date', 'lead_source', 'notes_text'],
      dtype='object')

In [5]:
# 4. Check the data type of every column using Pandas.

df.dtypes

Customer ID          object
Age                  object
income_usd           object
credit Score         object
tenure_years        float64
monthly_visits      float64
satisfaction        float64
City                 object
customer_segment     object
gender               object
is_active            object
churn_flag           object
signup_date          object
lead_source          object
notes_text           object
dtype: object

In [6]:
# 5. Calculate the number and percentage of missing values in every column.

df.isnull().sum()

Customer ID          20
Age                 331
income_usd          440
credit Score        360
tenure_years        258
monthly_visits      280
satisfaction        399
City                300
customer_segment    380
gender              240
is_active           340
churn_flag          160
signup_date         240
lead_source         420
notes_text          656
dtype: int64

In [8]:
(df.isnull().sum()/len(df)*100).round(2)

Customer ID          1.00
Age                 16.55
income_usd          22.00
credit Score        18.00
tenure_years        12.90
monthly_visits      14.00
satisfaction        19.95
City                15.00
customer_segment    19.00
gender              12.00
is_active           17.00
churn_flag           8.00
signup_date         12.00
lead_source         21.00
notes_text          32.80
dtype: float64

In [12]:
# 6. Find the rows where Customer ID is missing.

df[df["Customer ID"].isna()]

,Customer ID,Age,income_usd,credit Score,tenure_years,monthly_visits,satisfaction,City,customer_segment,gender,is_active,churn_flag,signup_date,lead_source,notes_text
162,NaN,18,61780.99213,715.4452325,10.137001,5.0,3.179153,Delhi,UNKNOWN,Female,NaN,No,2021-04-22,website,follow-up needed
226,NaN,18,58188.80528,737.9284458,15.655950,12.0,3.330254,Chennai,Consumer,Female,Y,NaN,2022-03-18,Referral,normal
300,NaN,NaN,93665.74378,703.9692987,12.723292,7.0,NaN,Pune,SMB,Female,1,No,NaN,Email,follow-up needed
421,NaN,29.6 years,NaN,641.3441152,8.940646,5.0,3.687539,NaN,Consumer,Female,1,No,2021-12-05,Unknown,NaN
770,NaN,20.39545706,92366.06753,767.8048841,4.524943,3.0,4.358065,Mumbai,Enterprise,f,N,No,2021-09-05,???,NaN
821,NaN,46.41996378,81119.71831,597.3307848,1.076200,5.0,4.346306,Delhi,consumer,f,1,Yes,2022-12-26,Email,NaN
876,NaN,36.57634009,76629.87047,699.109735,4.977078,6.0,2.700057,Mumbai,consumer,M,N,Yes,2021-07-01,referral,good
993,NaN,47.54933612,NaN,NaN,0.693710,4.0,3.659781,NaN,Enterprise,NaN,NaN,No,2024-07-09,Referral,late payment
1023,NaN,NaN,34219.41505,NaN,3.779121,4.0,3.529211,Hyderabad,NaN,M,N,No,2023-07-05,Google Ads,ok
1188,NaN,28.97406958,NaN,744 pts,7.947965,8.0,2.379383,Hyderabad,Consumer,f,Yes,No,2026-06-06,NaN,urgent
1202,NaN,42.23152645,35310.77625,684.8618643,2.465432,6.0,4.979391,Delhi,SMB,m,1,No,2024-10-10,google_ads,late payment
1212,NaN,56.44358785,"$99,697",749.3298384,3.743193,6.0,NaN,NaN,NaN,M,Y,Yes,2024-07-18,WEB,NaN
1248,NaN,34.60645101,96811.19575,798.1150352,1.551247,5.0,3.288656,Mumbai,SMB.,M,N,No,2023-09-16,Social,follow-up needed
1338,NaN,26.5 years,"$89,682",692.0794813,1.877392,4.0,3.783551,Pune,Consumer,m,N,No,2023-12-04,WEB,NaN
1346,NaN,46.22898842,60122.78196,684.8548451,3.837557,2.0,4.267750,Mumbai,consumer,F,N,Yes,2023-01-01,referral,follow-up needed
1448,NaN,18,NaN,628.337014,7.137356,5.0,NaN,Pune,Enterprise,Female,no,NaN,2024-08-25,Google Ads,NaN
1451,NaN,47.20187446,28270.08329,549.3662455,3.019237,6.0,3.441021,Hyderabad,SMB,m,yes,Yes,2023-10-12,Unknown,good
1462,NaN,49.99203599,58348.28529,511.5806801,2.775352,NaN,NaN,Mumbai,SMB,Female,no,No,2024-07-07,NaN,NaN
1564,NaN,42.96550781,"$64,045",561 pts,4.549291,4.0,3.513904,Chennai,Consumer,m,No,No,03/08/2023,Email,NaN
1652,NaN,33.27510593,37475.10034,NaN,4.345689,11.0,-999.000000,Mumbai,SMB,f,NaN,NaN,2022-02-15,Social,ok

In [15]:
# 7. Remove leading/trailing whitespace from all column names and convert them to lowercase with underscores.

df.columns = df.columns.str.strip().str.lower().str.replace(" ","_")
df.columns

Index(['customer_id', 'age', 'income_usd', 'credit_score', 'tenure_years',
       'monthly_visits', 'satisfaction', 'city', 'customer_segment', 'gender',
       'is_active', 'churn_flag', 'signup_date', 'lead_source', 'notes_text'],
      dtype='object')

In [16]:
# 8. Identify duplicate Customer ID values and count how many duplicates exist.

df["customer_id"].duplicated().sum()

np.int64(19)

In [18]:
df["customer_id"].value_counts()[df["customer_id"].value_counts() > 1]

Series([], Name: count, dtype: int64)

In [21]:
# 9. Remove duplicate customer records while keeping the first occurrence.

df = df.drop_duplicates(subset = "customer_id",keep ="first")
df["customer_id"].duplicated().sum()

np.int64(0)

In [22]:
# 10.Find all unique values in the customer_segment column and identify inconsistent categories such as Consumer, consumer, consumer , etc.

df["customer_segment"].unique()

array(['consumer', 'Consumer', 'Enterprise', 'SMB', nan, 'SMB.',
       'UNKNOWN'], dtype=object)

In [23]:
df["customer_segment"].astype(str).str.strip().str.lower().value_counts()

customer_segment
consumer      779
smb           390
nan           378
enterprise    290
unknown        76
smb.           68
Name: count, dtype: int64

In [25]:
# 11.Clean the customer_segment column by standardizing capitalization and whitespace.

df["customer_segment"]=df["customer_segment"].str.strip().str.title()
df["customer_segment"]

0         Consumer
1         Consumer
2         Consumer
3       Enterprise
4       Enterprise
           ...
1995      Consumer
1996           Smb
1997          Smb.
1998           Smb
1999      Consumer
Name: customer_segment, Length: 1981, dtype: object

In [28]:
# 12.Find all unique values in the gender column and convert them into consistent categories such as Male and Female.

df["gender"].unique()

array([nan, 'Male', 'm', 'Female', 'M', 'F', 'f'], dtype=object)

In [31]:
df["gender"] = df["gender"].str.strip().str.title()
df["gender"].unique()

array([nan, 'Male', 'M', 'Female', 'F'], dtype=object)

In [38]:
# 13.Clean the is_active column so values such as Yes, yes, Y, 1 become 1, and No, no, N, 0 become 0.

df["is_active"] = (df["is_active"].astype(str).str.strip().str.lower().map({"yes":1,"y":1,"1":1,"no":0,"n":0,"0":0}))
df["is_active"].unique()

array([nan])

In [39]:
df["is_active"].value_counts()

Series([], Name: count, dtype: int64)

In [43]:
# 14.Convert the churn_flag column from categorical values (Yes/No) into a binary numerical column (1/0).

df["churn_flag"] = (df["churn_flag"].astype(str).str.strip().str.lower().map({"Yes":1,"No":0}))
df["churn_flag"].unique()

array([nan])

In [46]:
#15.Identify all values in income_usd that cannot be directly interpreted as numbers.

temp = pd.to_numeric(df["income_usd"],errors="coerce")
df[df["income_usd"].notna() & temp.isna()]["income_usd"].unique()

array(['$44,696', '$41,941', '$123,682', '$40,978', '$45,565', '$112,864',
       '$38,946', '$93,738', '$70,056', '$26,771', 'missing', '$48,959',
       '$36,410', '$86,520', '$88,847', '$88,960', '$50,211', '$104,630',
       '$72,142', '$34,864', '$130,837', '$90,730', '$29,657', '$60,407',
       '₹55k', '$506,709', '$71,214', '$191,997', '$35,341', '$171,139',
       '$65,761', '$30,152', '$47,631', '$319,924', '$46,216', '$49,366',
       '$78,703', '$44,955', '$76,860', '$50,094', '$129,799', '$32,702',
       '$33,399', '$19,760', '$146,497', '$30,746', '$107,324', '$19,808',
       'error', '$49,885', '$22,575', '$53,462', '$100,254', '$37,397',
       '$89,920', '$60,643', '$153,576', '$114,703', '$117,570',
       '$155,204', '$39,065', '$108,002', '$33,428', '$18,612', '$32,495',
       '$31,099', '$60,008', '$31,588', '$84,034', '$92,205', '$30,921',
       '$38,009', '$61,792', '$48,656', '$49,855', '$23,569', '$38,605',
       '$37,860', '$47,580', '$24,527', '$78,202', '$53,993', '$64,415',
       'not available', '$99,869', '$543,686', '$74,109', '$45,886',
       '$75,683', '$59,291', '$41,955', '$37,026', '$13,148', '$56,234',
       '$73,642', '$44,722', '$39,362', '$41,269', '$33,259', '$34,160',
       '$45,415', '$55,242', '$35,506', '$352,568', '$25,393', '$20,322',
       '$65,732', '$15,187', '$61,230', '$38,916', '$97,960', '$93,193',
       '$42,625', '$36,305', '$33,715', '$34,982', '$45,435', '$212,590',
       '$151,415', '$38,849', '$256,510', '$25,921', '$52,112',
       '$155,352', '$45,288', '$76,139', '$48,047', '$27,675', '$55,161',
       '$63,822', '$124,103', '$26,579', '$27,606', '$87,822', '$83,857',
       '$31,808', '$24,295', '$22,540', '$38,251', '$41,234', '$506,702',
       '$52,352', '$31,857', '$98,449', '$54,157', '$49,817', '$17,863',
       '$160,831', '$119,220', '$264,787', '$69,968', '$105,759',
       '$76,027', '$24,407', '$135,870', '$40,483', '$68,496', '$53,034',
       '$50,179', '$41,996', '$295,916', '$100,739', '$64,975', '$64,537',
       '$30,668', '$47,068', '$51,813', '$57,778', '$50,057', '$125,589',
       '$22,832', '$58,551', '$135,575', '$34,809', '$80,389', '$58,046'],
      dtype=object)

In [51]:
# 16.Clean income_usd by removing currency symbols, commas, and invalid text, then convert it to a numeric column using pd.to_numeric().

df["income_usd"] = df["income_usd"].astype(str).str.replace(r"[$,]","",regex = True).str.replace(r"[^\d.-]","",regex=True)
df["income_usd"] = pd.to_numeric(df["income_usd"],errors="coerce")
df["income_usd"].head()

0    28198.41033
1    61312.83129
2    44199.67124
3    56259.90961
4    31238.64196
Name: income_usd, dtype: float64

In [57]:
# 17.Clean the Age column so values such as "35 years" become numeric values.

df["age"] = pd.to_numeric(df["age"].astype(str).str.replace("years","").str.strip(),errors="coerce")
df["age"]

0       45.867417
1       47.765164
2             NaN
3       62.723578
4             NaN
          ...
1995    27.269512
1996    41.091685
1997    26.215767
1998    42.300000
1999    59.256095
Name: age, Length: 1981, dtype: float64

In [60]:
# 18.Identify unrealistic age values using NumPy/Pandas and replace them with NaN.

import numpy as np
df["age"] = df["age"].where(df["age"].between(18,100),np.nan)
df["age"]

0       45.867417
1       47.765164
2             NaN
3       62.723578
4             NaN
          ...
1995    27.269512
1996    41.091685
1997    26.215767
1998    42.300000
1999    59.256095
Name: age, Length: 1981, dtype: float64

In [64]:
# 19.Clean the credit_score column by removing text such as "pts" and converting the column to numeric.

df["credit_score"] = pd.to_numeric(df["credit_score"].astype(str).str.replace("pts", "").str.strip(),errors="coerce")
df["credit_score"]

0       660.562918
1       838.000000
2       613.132775
3       720.236986
4       549.183252
           ...
1995    633.974006
1996    701.720106
1997    647.799336
1998    521.000000
1999    576.739074
Name: credit_score, Length: 1981, dtype: float64

In [66]:
#20.Detect outliers in income_usd using the IQR method with NumPy/Pandas.

import numpy as np
Q1 = df["income_usd"].quantile(0.25)
Q3 = df["income_usd"].quantile(0.75)
IQR = Q3-Q1
lower = Q1 - 1.5 * IQR
upper = Q3 - 1.5 * IQR
outlier = df[(df["income_usd"] < lower) | (df["income_usd"] > upper)]
outlier

,customer_id,age,income_usd,credit_score,tenure_years,monthly_visits,satisfaction,city,customer_segment,gender,is_active,churn_flag,signup_date,lead_source,notes_text
0,CUST-01861,45.867417,28198.41033,660.562918,5.274076,5.0,3.382150,Pune,Consumer,NaN,NaN,NaN,2026-03-11,Referral,NaN
1,CUST-00354,47.765164,61312.83129,838.000000,5.632826,9.0,NaN,Hyderabad,Consumer,Male,NaN,NaN,NaN,website,follow-up needed
2,CUST-01334,NaN,44199.67124,613.132775,NaN,8.0,4.195157,Mumbai,Consumer,M,NaN,NaN,2024-09-20,Email,NaN
3,CUST-00906,62.723578,56259.90961,720.236986,2.029634,4.0,NaN,Chennai,Enterprise,M,NaN,NaN,2023-07-12,Website,normal
4,CUST-01290,NaN,31238.64196,549.183252,2.648626,5.0,3.117326,Mumbai,Enterprise,Male,NaN,NaN,2024-08-06,NaN,???
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,CUST-01131,27.269512,79436.89335,633.974006,14.007477,NaN,3.556073,Bengaluru,Consumer,M,NaN,NaN,2024-02-26,email,normal
1996,CUST-01295,41.091685,39912.37991,701.720106,0.673289,8.0,2.963094,Pune,Smb,M,NaN,NaN,2024-08-11,Website,good
1997,CUST-00861,26.215767,24522.26545,647.799336,2.026485,12.0,3.079259,Hyderabad,Smb.,F,NaN,NaN,2023-05-27,WEB,???
1998,CUST-01460,42.300000,84103.61056,521.000000,7.168156,5.0,3.579652,Hyderabad,Smb,NaN,NaN,NaN,2025-01-26,Email,ok
1999,CUST-01127,59.256095,53723.87392,576.739074,9.720663,NaN,1.100520,Pune,Consumer,NaN,NaN,NaN,2024-02-22,???,good

In [68]:
# 21.Detect outliers in credit_score using the IQR method.

Q1 = df["credit_score"].quantile(0.25)
Q3 = df["credit_score"].quantile(0.75)
IQR = Q3 - Q1
lower = Q1 - 1.5 * IQR
upper = Q3 - 1.5 * IQR
outlier = df[(df["credit_score"]<lower)|(df["credit_score"]>upper)]
outlier

,customer_id,age,income_usd,credit_score,tenure_years,monthly_visits,satisfaction,city,customer_segment,gender,is_active,churn_flag,signup_date,lead_source,notes_text
0,CUST-01861,45.867417,28198.41033,660.562918,5.274076,5.0,3.382150,Pune,Consumer,NaN,NaN,NaN,2026-03-11,Referral,NaN
1,CUST-00354,47.765164,61312.83129,838.000000,5.632826,9.0,NaN,Hyderabad,Consumer,Male,NaN,NaN,NaN,website,follow-up needed
2,CUST-01334,NaN,44199.67124,613.132775,NaN,8.0,4.195157,Mumbai,Consumer,M,NaN,NaN,2024-09-20,Email,NaN
3,CUST-00906,62.723578,56259.90961,720.236986,2.029634,4.0,NaN,Chennai,Enterprise,M,NaN,NaN,2023-07-12,Website,normal
4,CUST-01290,NaN,31238.64196,549.183252,2.648626,5.0,3.117326,Mumbai,Enterprise,Male,NaN,NaN,2024-08-06,NaN,???
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1994,CUST-01096,52.715515,29481.38718,780.970556,4.792256,NaN,3.717755,Delhi,Consumer,Female,NaN,NaN,2024-01-21,Unknown,???
1995,CUST-01131,27.269512,79436.89335,633.974006,14.007477,NaN,3.556073,Bengaluru,Consumer,M,NaN,NaN,2024-02-26,email,normal
1996,CUST-01295,41.091685,39912.37991,701.720106,0.673289,8.0,2.963094,Pune,Smb,M,NaN,NaN,2024-08-11,Website,good
1997,CUST-00861,26.215767,24522.26545,647.799336,2.026485,12.0,3.079259,Hyderabad,Smb.,F,NaN,NaN,2023-05-27,WEB,???
1999,CUST-01127,59.256095,53723.87392,576.739074,9.720663,NaN,1.100520,Pune,Consumer,NaN,NaN,NaN,2024-02-22,???,good

In [69]:
# 22.Detect suspicious values such as -999 and 99999 in tenure_years and satisfaction.

suspicious_values = [-999,99999]
print("suspicious tenure_years:")
print(df[df["tenure_years"].isin(suspicious_values)])
print("suspicious satisfaction:")
print(df[df["satisfaction"].isin(suspicious_values)])

suspicious tenure_years:
     customer_id        age   income_usd  credit_score  tenure_years  \
29    CUST-00030  43.200000  42283.10103    725.850544        -999.0
161   CUST-00835  28.965297  72142.00000    697.323368       99999.0
358   CUST-01379  41.494777          NaN    659.782901       99999.0
533   CUST-00708  44.700000  11398.68596    755.971558       99999.0
906   CUST-01934  53.500000          NaN    632.099672        -999.0
1136  CUST-00984  46.826997  63430.28242    560.290632       99999.0
1421  CUST-00769        NaN  86615.23189    515.314350       99999.0
1627  CUST-01823        NaN          NaN    638.741115       99999.0
1728  CUST-01759  25.631396          NaN    749.194908        -999.0
1959  CUST-01083  43.191133  62398.19731    597.000000        -999.0

      monthly_visits  satisfaction       city customer_segment  gender  \
29               5.0      3.391060  Hyderabad       Enterprise       F
161              7.0      3.449143      Delhi         Consumer       F
358              5.0      2.956488    Chennai         Consumer  Female
533              NaN      3.083209      Delhi         Consumer  Female
906              3.0      3.911122  Hyderabad       Enterprise  Female
1136             5.0      3.640326  Bengaluru         Consumer       F
1421             5.0      3.601668        NaN              Smb  Female
1627             2.0      5.000000     Mumbai              Smb       M
1728             NaN           NaN  Hyderabad              Smb    Male
1959             7.0      4.020120        NaN          Unknown  Female

      is_active  churn_flag signup_date lead_source    notes_text
29          NaN         NaN  2021-01-30         NaN        urgent
161         NaN         NaN  2023-04-30         ???           VIP
358         NaN         NaN  2024-11-05       Email        normal
533         NaN         NaN  2022-12-22  google_ads           NaN
906         NaN         NaN         NaN         NaN           NaN
1136        NaN         NaN  2023-09-29      Social           VIP
1421        NaN         NaN  2023-02-22     Unknown           VIP
1627        NaN         NaN  2026-01-31         NaN  late payment
1728        NaN         NaN  2025-11-27         NaN           NaN
1959        NaN         NaN  2024-01-08         WEB           NaN
suspicious satisfaction:
     customer_id        age   income_usd  credit_score  tenure_years  \
459   CUST-00484  44.969325  53926.90802           NaN      9.649929
730   CUST-00215  34.067923  34151.42487    697.255770      2.008998
788   CUST-01193  34.920151          NaN    797.594511           NaN
894   CUST-00637  35.720914  45890.95396    805.849093      1.206751
948   CUST-00911  28.978930          NaN    636.000000      3.683234
1165  CUST-00674  22.198037  71822.09888    528.205800      5.782927
1499  CUST-01004  45.606925          NaN           NaN      2.083318
1657  CUST-01891  50.294152  28185.47045    827.000000      3.909337
1872  CUST-01181  22.154132  31958.96865    569.916053      6.100963

      monthly_visits  satisfaction       city customer_segment  gender  \
459              7.0        -999.0     Mumbai       Enterprise  Female
730              5.0       99999.0  Hyderabad         Consumer       M
788              5.0       99999.0  Bengaluru              Smb       F
894              6.0        -999.0      Delhi       Enterprise       F
948              NaN       99999.0       Pune              NaN    Male
1165            12.0       99999.0  Bengaluru         Consumer       F
1499             3.0        -999.0    Kolkata              Smb       M
1657             6.0       99999.0  Hyderabad       Enterprise    Male
1872            10.0       99999.0       Pune              Smb       F

      is_active  churn_flag signup_date lead_source    notes_text
459         NaN         NaN  2022-05-08         NaN          good
730         NaN         NaN  2021-08-07         NaN          good
788         NaN         NaN  2024-04-29  Google Ads           NaN
894         NaN         NaN  11/10/2022     Unknown           NaN
948         NaN         NaN  2023-07-17     Website  late payment
1165        NaN         NaN         NaN      Social           NaN
1499        NaN         NaN  2023-10-20    referral           NaN
1657        NaN         NaN  10/04/2026         WEB  late payment
1872        NaN         NaN  2024-04-17      Social        urgent

In [71]:
# 23.Replace invalid/suspicious numerical values with NaN.

import numpy as np
df["tenure_years"] = df["tenure_years"].replace([-999,99999],np.nan)
df["satisfaction"] = df["satisfaction"].replace([-999,99999],np.nan)
df[["tenure_years","satisfaction"]]

      tenure_years  satisfaction
0         5.274076      3.382150
1         5.632826           NaN
2              NaN      4.195157
3         2.029634           NaN
4         2.648626      3.117326
...            ...           ...
1995     14.007477      3.556073
1996      0.673289      2.963094
1997      2.026485      3.079259
1998      7.168156      3.579652
1999      9.720663      1.100520

[1981 rows x 2 columns]

In [73]:
# 24.Fill missing numerical values using the median of each numerical column.

num_cols = df.select_dtypes(include ="number").columns
df[num_cols] = df[num_cols].fillna(df[num_cols].median())
df[num_cols].isna().sum()

age                  0
income_usd           0
credit_score         0
tenure_years         0
monthly_visits       0
satisfaction         0
is_active         1981
churn_flag        1981
dtype: int64

In [77]:
# 25.Fill missing categorical values using the mode of each categorical column.

cat_cols = df.select_dtypes(include = "object").columns
for col in  cat_cols:
    df[col].fillna(df[col].mode()[0])
df[cat_cols].isna().sum()

customer_id           1
city                297
customer_segment    378
gender              239
signup_date         239
lead_source         418
notes_text          648
dtype: int64

In [80]:
# 26.Clean the signup_date column, which contains multiple date formats and invalid dates, and convert it to Pandas datetime.

df["signup_date"] = pd.to_datetime(df["signup_date"],errors="coerce")
df["signup_date"].head()

0   NaT
1   NaT
2   NaT
3   NaT
4   NaT
Name: signup_date, dtype: datetime64[ns]

In [81]:
# 27.Find rows where signup_date could not be converted into a valid date.

invalid_dates = df[df["signup_date"].isna()]
invalid_dates

,customer_id,age,income_usd,credit_score,tenure_years,monthly_visits,satisfaction,city,customer_segment,gender,is_active,churn_flag,signup_date,lead_source,notes_text
0,CUST-01861,45.867417,28198.41033,660.562918,5.274076,5.0,3.382150,Pune,Consumer,NaN,NaN,NaN,NaT,Referral,NaN
1,CUST-00354,47.765164,61312.83129,838.000000,5.632826,9.0,3.744948,Hyderabad,Consumer,Male,NaN,NaN,NaT,website,follow-up needed
2,CUST-01334,37.960683,44199.67124,613.132775,4.701753,8.0,4.195157,Mumbai,Consumer,M,NaN,NaN,NaT,Email,NaN
3,CUST-00906,62.723578,56259.90961,720.236986,2.029634,4.0,3.744948,Chennai,Enterprise,M,NaN,NaN,NaT,Website,normal
4,CUST-01290,37.960683,31238.64196,549.183252,2.648626,5.0,3.117326,Mumbai,Enterprise,Male,NaN,NaN,NaT,NaN,???
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,CUST-01131,27.269512,79436.89335,633.974006,14.007477,6.0,3.556073,Bengaluru,Consumer,M,NaN,NaN,NaT,email,normal
1996,CUST-01295,41.091685,39912.37991,701.720106,0.673289,8.0,2.963094,Pune,Smb,M,NaN,NaN,NaT,Website,good
1997,CUST-00861,26.215767,24522.26545,647.799336,2.026485,12.0,3.079259,Hyderabad,Smb.,F,NaN,NaN,NaT,WEB,???
1998,CUST-01460,42.300000,84103.61056,521.000000,7.168156,5.0,3.579652,Hyderabad,Smb,NaN,NaN,NaN,NaT,Email,ok
1999,CUST-01127,59.256095,53723.87392,576.739074,9.720663,6.0,1.100520,Pune,Consumer,NaN,NaN,NaN,NaT,???,good

In [87]:
# 28.Clean the lead_source column by standardizing values such as Website, website, WEB, Referral, referral , Google Ads, and google_ads.

df["lead_source"] = df["lead_source"].str.lower().str.strip()
df["lead_source"] = df["lead_source"].replace({"web":"website","website":"website","referral":"referral","google_ads":"google ads","google ads":"google ads"})
df["lead_source"].value_counts()

lead_source
website       380
referral      284
email         261
google ads    239
???           140
social        138
unknown       121
Name: count, dtype: int64

In [96]:
# 29.Create a final cleaned DataFrame containing:
#• cleaned column names
#• no duplicate IDs
#• standardized categorical values
#• numeric columns converted to numeric types
#• invalid values converted to NaN
#• missing values handled
#• detected outliers handled

df.columns = df.columns.str.lower().str.strip().str.replace(" ","_")
df = df.drop_duplicates(subset="customer_id")
num_cols = df.select_dtypes(include="number").columns
for col in num_cols:
    df[col] = pd.to_numeric(df[col],errors="coerce")
df["tenure_years"] = df["tenure_years"].replace([-999,99999],np.nan)
df["satisfaction"] = df["satisfaction"].replace([-999,99999],np.nan)
cat_cols = df.select_dtypes(include ="object").columns
for col in cat_cols:
    df[col] = df[col].str.lower().str.strip()
num_cols = df.select_dtypes(include="number").columns
for col in num_cols:
    df[col] = df[col].fillna(df[col].median())
cat_cols = df.select_dtypes(include ="object").columns
for col in cat_cols:
    df[col] = df[col].fillna(df[col].mode()[0])
final_df = df.copy()
final_df.head()

,customer_id,age,income_usd,credit_score,tenure_years,monthly_visits,satisfaction,city,customer_segment,gender,is_active,churn_flag,signup_date,lead_source,notes_text
0,cust-01861,45.867417,28198.41033,660.562918,5.274076,5.0,3.382150,pune,consumer,m,NaN,NaN,NaT,referral,normal
1,cust-00354,47.765164,61312.83129,838.000000,5.632826,9.0,3.744948,hyderabad,consumer,male,NaN,NaN,NaT,website,follow-up needed
2,cust-01334,37.960683,44199.67124,613.132775,4.701753,8.0,4.195157,mumbai,consumer,m,NaN,NaN,NaT,email,normal
3,cust-00906,62.723578,56259.90961,720.236986,2.029634,4.0,3.744948,chennai,enterprise,m,NaN,NaN,NaT,website,normal
4,cust-01290,37.960683,31238.64196,549.183252,2.648626,5.0,3.117326,mumbai,enterprise,male,NaN,NaN,NaT,website,???

In [97]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1981 entries, 0 to 1999
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customer_id       1981 non-null   object
 1   age               1981 non-null   float64
 2   income_usd        1981 non-null   float64
 3   credit_score      1981 non-null   float64
 4   tenure_years      1981 non-null   float64
 5   monthly_visits    1981 non-null   float64
 6   satisfaction      1981 non-null   float64
 7   city              1981 non-null   object
 8   customer_segment  1981 non-null   object
 9   gender            1981 non-null   object
 10  is_active         0 non-null      float64
 11  churn_flag        0 non-null      float64
 12  signup_date       0 non-null      datetime64[ns]
 13  lead_source       1981 non-null   object
 14  notes_text        1981 non-null   object
dtypes: datetime64[ns](1), float64(8), object(6)
memory usage: 247.6+ KB

In [98]:
final_df.isna().sum()

customer_id            0
age                    0
income_usd             0
credit_score           0
tenure_years           0
monthly_visits         0
satisfaction           0
city                   0
customer_segment       0
gender                 0
is_active           1981
churn_flag          1981
signup_date         1981
lead_source            0
notes_text             0
dtype: int64

In [99]:
# 30.Perform a final data-quality audit using Pandas and NumPy:
#• Check remaining missing values
#• Check duplicate rows
#• Check duplicate customer IDs
#• Check data types
#• Check numerical ranges
#• Check unique categorical values
#• Confirm the final dataset is ready for analysis/ML

final_df.isnull().sum()

customer_id            0
age                    0
income_usd             0
credit_score           0
tenure_years           0
monthly_visits         0
satisfaction           0
city                   0
customer_segment       0
gender                 0
is_active           1981
churn_flag          1981
signup_date         1981
lead_source            0
notes_text             0
dtype: int64

In [100]:
final_df.duplicated().sum()

np.int64(0)

In [101]:
final_df["customer_id"].duplicated().sum()

np.int64(1)

In [102]:
final_df.dtypes

customer_id                 object
age                        float64
income_usd                 float64
credit_score               float64
tenure_years               float64
monthly_visits             float64
satisfaction               float64
city                        object
customer_segment            object
gender                      object
is_active                  float64
churn_flag                 float64
signup_date         datetime64[ns]
lead_source                 object
notes_text                  object
dtype: object

In [103]:
final_df.select_dtypes(include=np.number).describe().T

,count,mean,std,min,25%,50%,75%,max
age,1981.0,37.881981,10.706104,18.000000,31.648732,37.960683,43.373765,9.974357e+01
income_usd,1981.0,67570.260778,73304.904193,55.000000,43304.150060,55533.057890,72221.176450,1.667567e+06
credit_score,1981.0,645.262212,89.282131,141.922798,605.018786,647.635751,694.395491,8.500000e+02
tenure_years,1981.0,5.414568,3.355542,0.073142,3.173005,4.701753,6.880952,2.000000e+01
monthly_visits,1981.0,6.399798,4.697483,0.000000,5.000000,6.000000,7.000000,8.000000e+01
satisfaction,1981.0,3.704254,0.743958,1.000000,3.300270,3.744948,4.139251,5.000000e+00
is_active,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
churn_flag,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [106]:
cat_cols = final_df.select_dtypes(include ="object").columns
for col in cat_cols:
    final_df[col].unique()
final_df.shape

(1981, 15)